### ISSUE TITLE
Assignment for 9/10

### ISSUE THREAD

**Issue by akothapa** [AmherstCollege/STAT495-Kothapalli-public#1]
![image](https://cloud.githubusercontent.com/assets/6481371/9750738/e88b63ea-5669-11e5-88f7-60535c16416b.jpg)

I miss my puppy :(

**Comment by niwang15** [comment]
Ah that's a cute puppy!

**Comment by FeiWangMHC** [comment]
Cute!

**Comment by FeiWangMHC** [comment]
Hey Anusha! Do you know when our presentation will be? Could you also give me your email address? Thank you! :)

**Comment by nicholasjhorton** [comment]
Your presentations will be on Tuesday, September 22nd.

Nick

> On Sep 10, 2015, at 11:12 AM, FeiWangMHC <notifications@github.com> wrote:
> 
> Hey Anusha! Do you know when our presentation will be? Could you also give me your email address? Thank you! :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by FeiWangMHC** [comment]
Thank you Nick!

**Comment by akothapa** [comment]
Hey Fei!
It's akothapa@umass.edu. Let's talk tomorrow after class if you're free?
